### ISSUE TITLE
Redirect madboulder.org to hosted website

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#16]
Redirect madboulder.org to hosted website

**Comment by juangallostra** [comment]
@asantacreu Azure's cheapest tier that would enable us to host there the website is approximately 11.23 euros / month. A new account is given 170 euros of free credit, which would allow us to run the website for more or less 15 months. I think this would be a good start. Furthermore, it will give us plenty of time to decide where to host it next (or keep going with Azure). 

![Captura](https://user-images.githubusercontent.com/9968427/64422519-91275a00-d0a4-11e9-85c8-35da9a05d935.PNG)


**Documentation**:
https://docs.microsoft.com/es-es/azure/app-service/app-service-web-tutorial-custom-domain 
and, more specifically section
https://docs.microsoft.com/es-es/azure/app-service/app-service-web-tutorial-custom-domain#map-your-domain

**Comment by juangallostra** [comment]
mmmm I think I misread the conditions and the free credit is only valid during the free trial period, which is 1 month (and for us it ends on the 11th of September) 😓

**Comment by juangallostra** [comment]
@asantacreu my free subscription to Azure has ended and the website is currently down... :sweat:

**Comment by asantacreu** [comment]
@juangallostra Can we explore the prices of other hosts and maybe try another free plan?

**Comment by juangallostra** [comment]
@asantacreu I've switched provider and deployed the web to [heroku](https://www.heroku.com) (see http://madboulder.herokuapp.com/). 

They offer a free tier of 550 free dyno (which I'm not sure yet of what does it mean) hours per month, which is the option I am currently using. They also offer DNS name resolution for free as well as a better integration with Github (see the new "environment" tab that has appeared on the repo: https://github.com/juangallostra/BetaLibrary/deployments).

We can try this solution for the moment.

**Comment by juangallostra** [comment]
See https://devcenter.heroku.com/articles/custom-domains for the documentation on how to add custom domains.

**Comment by asantacreu** [comment]
1. Confirm that you own the custom domain name. You can buy a custom domain name with a domain registration service.
2. Add the custom domain to your app with the heroku domains:add command.
3. Look up the Heroku-supplied DNS target for the custom domain using the heroku domains command.
4. Configure your app’s DNS provider to point to the Heroku-supplied DNS target.
5. Confirm that your app is accessible via the custom domain. There might be a delay while DNS changes propagate.


You need to go through steps 1, 2 and 3 and tell me the DNS Target. Then I'll do step 4 and add them to out domain provider.

**Comment by juangallostra** [comment]
@asantacreu here you have it!

| Domain Name        | DNS Record Type | DNS Target                                          |
|--------------------|-----------------|-----------------------------------------------------|
| www.madboulder.org | CNAME           | basic-pepper-7ul9icdvn3oyhurerspt4xzw.herokudns.com |
| madboulder.org     | ALIAS or ANAME  | warm-melon-thqloj2jju09xppl8ihyriyr.herokudns.com   |

**Comment by juangallostra** [comment]
@asantacreu I hope to have this working in the near future. I have changed the DNS so that they are handled by Cloudfare, which allows root domains (such as madboulder.org) to be resolved to a CNAME instead of an A record (which has to be an IP and heroku doesn't provide static IPs)

**Comment by juangallostra** [comment]
@asantacreu I think it is working now! 💪 If you can check it and confirm it I will close the issue.

**Comment by juangallostra** [comment]
I have checked it and it works 👍 
Closing the issue.
