### ISSUE TITLE
Create an organization in GitHub

### ISSUE THREAD

**Issue by juangallostra** [MadBoulder/BetaLibrary#40]
@asantacreu I think it might be a good idea to create an organization in GitHub named MadBoulder and move the repository there. What do you think?

**Comment by asantacreu** [comment]
@juangallostra Yes! I Agree.

**Comment by juangallostra** [comment]
@asantacreu should I go on and create it? Or do you want to create it?

**Comment by asantacreu** [comment]
@juangallostra Let me try!

**Comment by asantacreu** [comment]
@juangallostra Created! You can start the migration :)

**Comment by juangallostra** [comment]
Nice! Maybe it is a good idea to add MadBoulder's Logo as the organization image.

**Comment by asantacreu** [comment]
Done!

**Comment by juangallostra** [comment]
One more thing @asantacreu. I currently don't a lot of permissions on MadBoulder's organization (due to my role being member). Maybe you can change it so that it is easier for me to manage the repo once migrated.

**Comment by asantacreu** [comment]
@juangallostra You're now an owner :)

**Comment by juangallostra** [comment]
@asantacreu  thanks! I just moved the repo.
