### ISSUE TITLE
Stats summary section in home page

### ISSUE THREAD

**Issue by juangallostra** [MadBoulder/BetaLibrary#51]
@asantacreu it might be cool to have some sort of stats summary in the home page. We can show there (for example) the current number of Beta videos and Bouldering areas.

**Comment by asantacreu** [comment]
Its a nice Idea! In general we could think of a Home page.
This would also be interesting for each zone to have  a summary of the betas and sectors.

**Comment by juangallostra** [comment]
@asantacreu what about something like this?

![Selection_022](https://user-images.githubusercontent.com/9968427/71717144-601f2200-2e17-11ea-85da-d1bad915f602.png)

**Comment by juangallostra** [comment]
Maybe the "Estadistiques" title is redundant and is not required...

**Comment by juangallostra** [comment]
This is how it looks without the section title:

![Selection_024](https://user-images.githubusercontent.com/9968427/71717341-14b94380-2e18-11ea-8db9-eae3ee551408.png)

**Comment by asantacreu** [comment]
@juangallostra Right, title not needed IMO

**Comment by juangallostra** [comment]
Closing as per #61
