### ISSUE TITLE
Add "Beta Name + Zone" in email's subject.

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#56]
Add "Beta Name + Zone + Author" in email's subject when a new beta is sent.

The current subject "New Beta!" may become a pain to manage.

**Comment by asantacreu** [comment]
@juangallostra If you could also change the email receiver to aniolsantacreusalva@gmail.com

**Comment by juangallostra** [comment]
@asantacreu changed 👍

**Comment by juangallostra** [comment]
@asantacreu should then climber become a mandatory field?

**Comment by asantacreu** [comment]
@juangallostra I don't think it's necessary for the moment. In the email it will appear blank when there's no author.

**Comment by juangallostra** [comment]
Closed as per #57
