### ISSUE TITLE
Message of "file sent OK" after submit is clicked

### ISSUE THREAD

**Issue by juangallostra** [MadBoulder/BetaLibrary#58]
After a file has been uploaded and the email sent, show some sign of success to the user such as "file sent OK".

**Comment by juangallostra** [comment]
The whole process would look like:

![success](https://user-images.githubusercontent.com/9968427/70696621-5e54b980-1cc4-11ea-90a7-2f864593ad3f.gif)

**Comment by asantacreu** [comment]
@juangallostra Looks awesome! but there sould be a "Send another" button also I think.

The required fields should have an asterisk or something..

**Comment by juangallostra** [comment]
@asantacreu something like this?

![Captura](https://user-images.githubusercontent.com/9968427/70698741-60207c00-1cc8-11ea-8caa-8f076622f8d7.PNG)

**Comment by juangallostra** [comment]
Closing as per PR #59
