### ISSUE TITLE
Make stats section smaller in mobile

### ISSUE THREAD

**Issue by juangallostra** [MadBoulder/BetaLibrary#62]
When visiting the page from a smartphone the stats section is too big

**Comment by juangallostra** [comment]
@asantacreu I've changed the stats section so that it is smaller when accessing the webpage via mobile. A preview is shown below:

![mobile](https://user-images.githubusercontent.com/9968427/71909635-b8845580-3170-11ea-9557-34e4c16619a0.PNG)

If this is ok, I will close the issue.

**Comment by asantacreu** [comment]
@juangallostra It is ok for me

**Comment by juangallostra** [comment]
Closing as per e6f3bdbad5034953d0a10c9d2dfcc97e605946c5
