### ISSUE TITLE
Add option to show ortho map in addition of topo

### ISSUE THREAD

**Issue by asantacreu** [MadBoulder/BetaLibrary#67]
Add option to show ortho map in addition of topo

**Comment by juangallostra** [comment]
@asantacreu something like this? There are now to layers on the map:
The original one:
![original_map](https://user-images.githubusercontent.com/9968427/76399805-8fa25b80-637f-11ea-86d3-e17b3506ed9f.PNG)
And a satellite view:
![satellite_map](https://user-images.githubusercontent.com/9968427/76399831-9b8e1d80-637f-11ea-9199-dac7e23a8969.PNG)

There is a layer control to switch between the two, as well as providing the option to activate/deactivate the rest of layers.

**Comment by asantacreu** [comment]
@juangallostra Exactly!
